#!/usr/bin/awk -f
{
if ((x=index($1,"@")) > 0)
{        
username = substr($1,1,x-1);        
hostname = substr($1,x+1,length($1));
printf("username = %s, hostname = %s\n", username, hostname);    
}
}
